name: Drupal_CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install

   - name: Check coding standards for modules and theme
     uses: docker://hussainweb/drupalqa:php7.4
     with:
       args: phpcs --standard="Drupal,DrupalPractice" -n --extensions="php,module,install,theme" web/themes/custom web/modules/custom --ignore=web/themes/*/dist/,web/themes/*/Gulpfile.js,web/themes/*/node_modules/
